"""add form_pre_cadastro table

Revision ID: 00857168b00b
Revises: 41aa03703367
Create Date: 2025-05-13 14:28:04.710097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00857168b00b'
down_revision = '41aa03703367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor_pre_cadastro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=255), nullable=False),
    sa.Column('nome_representante', sa.String(length=255), nullable=False),
    sa.Column('cpf_representante', sa.String(length=14), nullable=False),
    sa.Column('email_representante', sa.String(length=255), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('complemento', sa.String(length=255), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('fonte_conhecimento', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_pre_cadastro', sa.DateTime(), nullable=True),
    sa.Column('ip_cadastro', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('excluido', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fornecedor_pre_cadastro')
    # ### end Alembic commands ###
