"""add table_link_form

Revision ID: 41aa03703367
Revises: 803260f773dc
Create Date: 2025-05-13 11:46:06.871902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41aa03703367'
down_revision = '803260f773dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('parceiro_id', sa.Integer(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('excluido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parceiro_id'], ['parceiro.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_link')
    # ### end Alembic commands ###
