"""empty message

Revision ID: b52f337b5e5e
Revises: a0c1b2da6f50
Create Date: 2025-03-20 18:15:17.313514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52f337b5e5e'
down_revision = 'a0c1b2da6f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedor_nota', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_aviso_expiracao', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedor_nota', schema=None) as batch_op:
        batch_op.drop_column('email_aviso_expiracao')

    # ### end Alembic commands ###
