"""empty message

Revision ID: bf34cffed246
Revises: 
Create Date: 2025-03-14 15:50:05.082423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf34cffed246'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedor_nota', schema=None) as batch_op:
        batch_op.alter_column('tipo_operacao',
               existing_type=mysql.VARCHAR(length=51),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'parceiro_sacado'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedor_nota', schema=None) as batch_op:
        batch_op.alter_column('tipo_operacao',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=51),
               existing_nullable=False,
               existing_server_default=sa.text("'parceiro_sacado'"))

    # ### end Alembic commands ###
