"""empty message

Revision ID: fbafd78d5174
Revises: 9b9fc99b4d42
Create Date: 2025-03-21 17:25:41.032933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fbafd78d5174'
down_revision = '9b9fc99b4d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('notificacao_fornecedor_incompleto_auto')
        batch_op.drop_column('notificacao_nota_expirar_auto')
        batch_op.drop_column('habilitar_retorno_auto')
        batch_op.drop_column('notificacao_nota_disponivel_auto')
        batch_op.drop_column('habilitar_fornecedor_auto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habilitar_fornecedor_auto', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notificacao_nota_disponivel_auto', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('habilitar_retorno_auto', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notificacao_nota_expirar_auto', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notificacao_fornecedor_incompleto_auto', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
